Score Humanitec - New `route` support (#69)
* Update humanitec.score.yaml - new route support

* Update score.yaml - New route support

* Update score.yaml

* Update score.yaml - workaround

* humctl 0.1.0

* Update score.yaml - raise errors for now

* Update open-pr.yml - catch failed status

* Update open-pr.yml - display errors

* Update open-pr.yml

* Update open-pr.yml

* Update open-pr.yml - elif

* Update open-pr.yml - errors formatting

* Update open-pr.yml

* Update open-pr.yml

* Update open-pr.yml

* Update open-pr.yml

* Update score.yaml

* Update open-pr.yml - ${{ github.env }}

* Update push-tag.yml - ${{ github.* }}

diff --git a/.github/workflows/open-pr.yml b/.github/workflows/open-pr.yml
--- a/.github/workflows/open-pr.yml
+++ b/.github/workflows/open-pr.yml
@@ -156,7 +156,7 @@ jobs:
         run: |
           echo "IMAGE_DIGEST=$(oras manifest fetch ${{ env.IMAGE_NAME }}:${{ env.ENVIRONMENT_ID }} \
               --descriptor \
-              | jq -r .digest)" >> $GITHUB_ENV
+              | jq -r .digest)" >> ${{ github.env }}
       - name: install score-humanitec
         uses: score-spec/setup-score@v2
         with:
@@ -179,26 +179,30 @@ jobs:
       - name: wait for deployment
         run: |
           sleep 1
-
           IS_DONE=false
-
+          CURRENT_STATUS=""
           while [ "$IS_DONE" = false ]; do
             CURRENT_STATUS=$(.github/workflows/bin/humctl get environment ${{ env.ENVIRONMENT_ID }} -o json \
               --token ${{ secrets.HUMANITEC_TOKEN }} \
               --context /orgs/${{ secrets.HUMANITEC_ORG }}/apps/${{ vars.APP_NAME }} \
               | jq -r .object.last_deploy.status)
-            
-            INPROGRESS="in progress"
-
-            if [ "$CURRENT_STATUS" = "$INPROGRESS" ]; then
+            if [ "$CURRENT_STATUS" = "in progress" ]; then
               echo "Deployment still in progress..."
               sleep 1
+            elif [ "$CURRENT_STATUS" = "failed" ]; then
+              echo "Deployment failed!"
+              IS_DONE=true
             else
-              echo "Deployment complete!"
+              echo "Deployment successfully completed!"
               IS_DONE=true
             fi
           done
+          echo $CURRENT_STATUS
+          if [ "$CURRENT_STATUS" = "failed" ]; then
+              exit 1
+          fi
       - name: build comment message
+        if: ${{ always() }}
         run: |
           ENV_URL=$(jq -r ".metadata.url" score_output.json)
           DEPLOYMENT_ID=$(jq -r ".id" score_output.json)
@@ -207,8 +211,35 @@ jobs:
                       --context /orgs/${{ secrets.HUMANITEC_ORG }}/apps/${{ vars.APP_NAME }}/envs/${{ env.ENVIRONMENT_ID }} -o json \
                       | jq -r '. | map(. | select(.object.type == "dns")) | map((.object.res_id | split(".") | .[1]) + ": [" + .object.resource.host + "](https://" + .object.resource.host + ")") | join("\n")')
           
-          echo "## Deployment Complete for ${{ env.ENVIRONMENT_NAME }}! :tada:" >> pr_message.txt
-          echo "" >> pr_message.txt
+          DEPLOYMENT_ERRORS=$(.github/workflows/bin/humctl get deployment-error \
+              --token ${{ secrets.HUMANITEC_TOKEN }} \
+              --context /orgs/${{ secrets.HUMANITEC_ORG }}/apps/${{ vars.APP_NAME }}/envs/${{ env.ENVIRONMENT_ID }} -o json)
+          if [ "$DEPLOYMENT_ERRORS" = "[]" ]; then
+            echo "## Deployment successfully completed for ${{ env.ENVIRONMENT_NAME }}! :tada:" >> pr_message.txt
+            echo "" >> pr_message.txt
+          else
+            echo "## Deployment failed for ${{ env.ENVIRONMENT_NAME }}! :x:" >> pr_message.txt
+            echo "" >> pr_message.txt
+            echo "### Errors:" >> pr_message.txt
+            echo "" >> pr_message.txt
+            echo '```json' >> pr_message.txt
+            echo "" >> pr_message.txt
+            echo "$DEPLOYMENT_ERRORS" | jq .[0].object.message -r >> pr_message.txt
+            echo "" >> pr_message.txt
+            echo '```' >> pr_message.txt
+            echo "" >> pr_message.txt
+            echo "<details><summary>Errors details</summary>" >> pr_message.txt
+            echo "" >> pr_message.txt
+            echo "### Errors details:" >> pr_message.txt
+            echo '```json' >> pr_message.txt
+            echo "" >> pr_message.txt
+            echo "$DEPLOYMENT_ERRORS" >> pr_message.txt
+            echo "" >> pr_message.txt
+            echo '```' >> pr_message.txt
+            echo "" >> pr_message.txt
+            echo "</details>" >> pr_message.txt
+            echo "" >> pr_message.txt
+          fi
           
           echo "### [View in Humanitec]($ENV_URL)" >> pr_message.txt
           echo "Deployment ID: $DEPLOYMENT_ID" >> pr_message.txt
@@ -245,6 +276,7 @@ jobs:
 
           cat pr_message.txt
       - name: comment pr
+        if: ${{ always() }}
         uses: thollander/actions-comment-pull-request@v2
         with:
           filePath: pr_message.txt  
