Update promote-env.yml - wait for deployment

diff --git a/.github/workflows/promote-env.yml b/.github/workflows/promote-env.yml
--- a/.github/workflows/promote-env.yml
+++ b/.github/workflows/promote-env.yml
@@ -32,4 +32,30 @@ jobs:
                   --org ${{ secrets.HUMANITEC_ORG }} \
                   --app ${{ vars.APP_NAME }}
           fi
-
+      - name: wait for deployment
+        run: |
+          sleep 1
+          IS_DONE=false
+          CURRENT_STATUS=""
+          while [ "$IS_DONE" = false ]; do
+            CURRENT_STATUS=$(humctl get deployment . -o json \
+              --token ${{ secrets.HUMANITEC_TOKEN }} \
+              --org ${{ secrets.HUMANITEC_ORG }} \
+              --app ${{ vars.APP_NAME }} \
+              --env ${{ github.event.inputs.environment }} \
+              | jq -r .status.status)
+            if [ "$CURRENT_STATUS" = "in progress" ]; then
+              echo "Deployment still in progress..."
+              sleep 1
+            elif [ "$CURRENT_STATUS" = "failed" ]; then
+              echo "Deployment failed!"
+              IS_DONE=true
+            else
+              echo "Deployment successfully completed!"
+              IS_DONE=true
+            fi
+          done
+          echo $CURRENT_STATUS
+          if [ "$CURRENT_STATUS" = "failed" ]; then
+              exit 1
+          fi
