Catch Runtime errors in push-tag too

diff --git a/.github/workflows/push-tag.yml b/.github/workflows/push-tag.yml
--- a/.github/workflows/push-tag.yml
+++ b/.github/workflows/push-tag.yml
@@ -139,23 +139,37 @@ jobs:
               --org ${{ secrets.HUMANITEC_ORG }} \
               --app ${{ vars.APP_NAME }} \
               --env ${{ env.ENVIRONMENT_ID }} -o json)
-          if [ "$DEPLOYMENT_ERRORS" = "[]" ]; then
+          RUNTIME_ERRORS=$(humctl api get /orgs/${{ secrets.HUMANITEC_ORG }}/apps/${{ vars.APP_NAME }}/envs/${{ env.ENVIRONMENT_ID }}/runtime \
+              --token ${{ secrets.HUMANITEC_TOKEN }} \
+              | grep '"status": "Failure"' -B 10 -A 1) \
+              || true
+          if [[ "$DEPLOYMENT_ERRORS" = "[]" && -z "$RUNTIME_ERRORS" ]]; then
             echo "## Deployment successfully completed for ${{ env.ENVIRONMENT_ID }}! :tada:"
             echo ""
           else
             echo "## Deployment failed for ${{ env.ENVIRONMENT_ID }}! :x:"
             echo ""
-            echo "### Errors:"
-            echo ""
-            echo "$DEPLOYMENT_ERRORS"
-            echo ""
+            
+            if [ "$DEPLOYMENT_ERRORS" != "[]" ]; then
+              echo "### Deployment errors:"
+              echo ""
+              echo "$DEPLOYMENT_ERRORS"
+              echo ""
+            fi
+
+            if [ -n "$RUNTIME_ERRORS" ]; then
+              echo "### Runtime errors:"
+              echo ""
+              echo "$RUNTIME_ERRORS"
+              echo ""
+            fi
           fi
           
           echo "### View in Humanitec: $ENV_URL"
           echo ""
           echo "### Deployment ID: $DEPLOYMENT_ID"
           echo ""
-          echo "### Domains:"
+          echo "### URLs:"
           echo ""
           echo "$DOMAINS"
           echo ""
